[package]
name = "gigica"
version = "0.1.0"
edition = "2021"

[lib]
name = "_gigica"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
numpy = "0.27.1"
ndarray = "0.17.1"
faer = "0.23.2"
